runtime: nodejs18
instance_class: F1
automatic_scaling:
  max_instances: 2

handlers:
  # CSS, JS, Images, Fonts
  - url: /(.*\.(css|js|map))$
    static_files: dist/\1
    upload: dist/.*\.(css|js|map)$
    expiration: "1h"

  - url: /(.*\.(png|jpg|jpeg|gif|ico|svg|webp))$
    static_files: dist/\1
    upload: dist/.*\.(png|jpg|jpeg|gif|ico|svg|webp)$
    expiration: "1d"

  - url: /(.*\.(woff|woff2|ttf|eot))$
    static_files: dist/\1
    upload: dist/.*\.(woff|woff2|ttf|eot)$
    expiration: "365d"


  # HTML files
  - url: /(.*\.(html))$
    static_files: dist/\1
    upload: dist/.*\.(html)$
    expiration: "5m"

  # React Router - catch all routes
  - url: /.*
    static_files: dist/index.html
    upload: dist/index.html
    secure: always